# Generated by Django 6.0 on 2025-12-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SChatapp", "0002_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_user",
            field=models.BooleanField(default=True),
        ),
    ]
